#!/usr/sbin/nft -f

flush ruleset

table inet lab {
    chain input {
        type filter hook input priority filter; policy accept;

        iif lo accept

        udp dport 1-65535 log prefix "UDP-HIT: " flags all counter accept

        ct state established,related accept
    }
}
